name: build

on:
  push:
    branches:
    - main

jobs:
  build-image:
    permissions:
      contents: read
      packages: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq -r .version package.json'
    - if: github.ref_type == 'tag'
      run: '[[ "$VERSION" = "$GITHUB_REF_NAME" ]]'
      env:
        VERSION: ${{ steps.version.outputs.value }}
    - if: github.ref_type != 'tag'
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args:
          VERSION=${{ steps.version.outputs.value }}-dev.${{ github.run_number }}
        tags: |
          ghcr.io/${{ github.repository }}:git-${{ github.sha }}
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}-dev.${{ github.run_number }}
          ghcr.io/${{ github.repository }}:latest
        cache-from:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache
        cache-to:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache,mode=max
    - if: github.ref_type == 'tag'
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args:
          VERSION=${{ steps.version.outputs.value }}
        tags: |
          ghcr.io/${{ github.repository }}:git-${{ github.sha }}
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
          ghcr.io/${{ github.repository }}:latest
        cache-from:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache
        cache-to:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache,mode=max

# cSpell: ignore buildx sergeysova
